# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import index_methods as module_0
import sympy.functions.elementary.exponential as module_1
import sympy.core.function as module_2
import sympy.core.expr as module_3


def test_case_0():
    none_type_0 = None
    var_0 = module_0.get_indices(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.get_contraction_structure(none_type_0)


def test_case_2():
    index_conformance_exception_0 = module_0.IndexConformanceException()


@pytest.mark.xfail(strict=True)
def test_case_3():
    index_conformance_exception_0 = module_0.IndexConformanceException()
    module_0.get_indices(index_conformance_exception_0)


def test_case_4():
    exp_base_0 = module_1.ExpBase()
    var_0 = exp_base_0.__add__(exp_base_0)
    var_1 = module_0.get_indices(var_0)


def test_case_5():
    application_0 = module_2.Application()
    var_0 = module_0.get_contraction_structure(application_0)


def test_case_6():
    application_0 = module_2.Application()
    var_0 = module_0.get_indices(application_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    exp_base_0 = module_1.ExpBase()
    module_0.get_indices(exp_base_0)


def test_case_8():
    exp_base_0 = module_1.ExpBase()
    var_0 = module_0.get_contraction_structure(exp_base_0)


def test_case_9():
    exp_base_0 = module_1.ExpBase()
    var_0 = exp_base_0.__add__(exp_base_0)
    var_1 = module_0.get_contraction_structure(var_0)


def test_case_10():
    exp_base_0 = module_1.ExpBase()
    var_0 = exp_base_0.__add__(exp_base_0)
    var_1 = var_0.count_ops(var_0)
    var_2 = module_0.get_indices(var_1)
    expr_0 = module_3.Expr()


def test_case_11():
    exp_base_0 = module_1.ExpBase()
    var_0 = exp_base_0.__add__(exp_base_0)
    var_1 = var_0.count_ops(var_0)
    var_2 = var_1.__rfloordiv__(exp_base_0)
    expr_0 = module_3.Expr()
    var_3 = module_0.get_contraction_structure(var_2)
