# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import from_array_to_matrix as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.identify_removable_identity_matrices(none_type_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.convert_array_to_matrix(none_type_0)
