# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import from_indexed_to_array as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"(=\n\xf9\x91; \xdc\xe1\xfcN\xff\x94%\xb6\xcc\xf9W"
    module_0.convert_indexed_to_array(bytes_0, bytes_0)


def test_case_1():
    bool_0 = False
    var_0 = module_0.convert_indexed_to_array(bool_0)
    assert var_0 is False
