# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import utilities as module_0


def test_case_0():
    dot_prod_simp_state_0 = module_0.DotProdSimpState()
    assert dot_prod_simp_state_0.state is None
