# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import maxima as module_0


def test_case_0():
    str_0 = "eval_aV1"
    var_0 = module_0.parse_maxima(str_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "sympy.core.symbol.Symbol"
    )


def test_case_1():
    maxima_helpers_0 = module_0.MaximaHelpers()


def test_case_2():
    str_0 = "\rv:k!"
    var_0 = module_0.parse_maxima(str_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "sympy.functions.combinatorial.factorials.factorial"
    )
    assert (
        f"{type(var_0.nargs).__module__}.{type(var_0.nargs).__qualname__}"
        == "sympy.sets.sets.FiniteSet"
    )
    assert len(var_0.nargs) == 1


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "\rv:k!"
    module_0.parse_maxima(str_0, str_0)
