# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import parabola as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.Parabola()


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    dict_0 = {bool_0: bool_0}
    module_0.Parabola(*dict_0)
