# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import refine as module_0
import sympy.logic.boolalg as module_1
import sympy.core.add as module_2


def test_case_0():
    none_type_0 = None
    var_0 = module_0.refine(none_type_0)


def test_case_1():
    boolean_0 = module_1.Boolean()
    var_0 = module_0.refine(boolean_0, boolean_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "sympy.logic.boolalg.BooleanTrue"
    )


def test_case_2():
    add_0 = module_2.Add()
    var_0 = module_0.refine(add_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "sympy.core.numbers.Zero"
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    boolean_0 = module_1.Boolean()
    var_0 = boolean_0.dummy_eq(boolean_0)
    bool_0 = True
    add_0 = boolean_0.__xor__(bool_0)
    module_0.refine(add_0)
