# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import euler as module_0
import sympy.core.basic as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.euler_equations(none_type_0, vars=none_type_0)


def test_case_1():
    none_type_0 = None
    with pytest.raises(TypeError):
        module_0.euler_equations(none_type_0, none_type_0, none_type_0)


def test_case_2():
    basic_0 = module_1.Basic()
    with pytest.raises(TypeError):
        module_0.euler_equations(basic_0, vars=basic_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    basic_0 = module_1.Basic()
    module_0.euler_equations(basic_0)


def test_case_4():
    basic_0 = module_1.Basic()
    str_0 = "xduhwhI"
    var_0 = module_0.euler_equations(basic_0, vars=str_0)
