# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import src.flask.templating as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.render_template_string(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.Environment(none_type_0)


def test_case_2():
    none_type_0 = None
    dispatching_jinja_loader_0 = module_0.DispatchingJinjaLoader(none_type_0)
    assert (
        f"{type(dispatching_jinja_loader_0).__module__}.{type(dispatching_jinja_loader_0).__qualname__}"
        == "src.flask.templating.DispatchingJinjaLoader"
    )
    assert dispatching_jinja_loader_0.app is None


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "P?-O\x0b;\n?0X7]Qg"
    module_0.render_template(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "zb+plu0!*'=hk[hG<81"
    module_0.stream_template(str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "$\x0bb)~.-53"
    module_0.stream_template_string(str_0)
